// 由 build.py 从 config/ 自动生成，请勿手改。改内容请编辑 config/ 后重跑 build.py
window.CARDS = [
  {
    "id": "Red_Base_Leader_01",
    "color": "红",
    "colorKey": "red",
    "type": "character",
    "role": "Leader",
    "name": "雪球",
    "animal": "猪",
    "recruit": "1",
    "passive": "雪球的影响力恒为公众资源数。",
    "declName": "革命者万岁",
    "declCost": "0",
    "declEffect": "你的红色角色夺取对位1个资源。",
    "bound": "风车小队",
    "tags": "",
    "image": "assets/cards/Red_Base_Leader_01.webp",
    "altImage": null,
    "pairId": "Red_Base_Sub_01"
  },
  {
    "id": "Red_Base_Sub_01",
    "color": "红",
    "colorKey": "red",
    "type": "character",
    "role": "Sub",
    "name": "风车小队",
    "animal": "猪",
    "recruit": "2",
    "passive": "你的红色角色影响力+1.",
    "declName": "风车计划",
    "declCost": "0",
    "declEffect": "你的红色角色的对位{消耗1}。",
    "bound": "雪球",
    "tags": "",
    "image": "assets/cards/Red_Base_Sub_01.webp",
    "altImage": null,
    "pairId": "Red_Base_Leader_01"
  },
  {
    "id": "Red_Base_Leader_02",
    "color": "红",
    "colorKey": "red",
    "type": "character",
    "role": "Leader",
    "name": "老少校",
    "animal": "猪",
    "recruit": "3",
    "passive": "老少校离场时，你的其他角色夺取对位1个资源。",
    "declName": "英格兰之兽",
    "declCost": "2",
    "declEffect": "选择1名资源最高的角色，其{消耗X}（X为场上资源最高与最低的差值）",
    "bound": "动物主义/七诫",
    "tags": "",
    "image": "assets/cards/Red_Base_Leader_02.webp",
    "altImage": null,
    "pairId": "Red_Base_Sub_02"
  },
  {
    "id": "Red_Base_Sub_02",
    "color": "红",
    "colorKey": "red",
    "type": "function",
    "role": "Sub",
    "name": "动物主义/七诫",
    "meansName": "动物主义",
    "meansCost": "2",
    "meansEffect": "均分场上所有角色的资源，无法均分的部分进入公共资源。",
    "billName": "七诫",
    "billEffect": "资源最高的所有角色影响力-4",
    "bound": "老少校",
    "image": "assets/cards/Red_Base_Sub_02.webp",
    "altImage": null,
    "pairId": "Red_Base_Leader_02"
  },
  {
    "id": "Red_Base_Leader_03",
    "color": "红",
    "colorKey": "red",
    "type": "character",
    "role": "Leader",
    "name": "红冠母亲团",
    "animal": "禽",
    "recruit": "2",
    "passive": "红冠母亲团每次移动后，其对位{消耗2}。",
    "declName": "游鸡战",
    "declCost": "1",
    "declEffect": "{勤奋}；移动红冠母亲团。",
    "bound": "扰动战术/一切为了孩子",
    "tags": "",
    "image": "assets/cards/Red_Base_Leader_03.webp",
    "altImage": null,
    "pairId": "Red_Base_Sub_03"
  },
  {
    "id": "Red_Base_Sub_03",
    "color": "红",
    "colorKey": "red",
    "type": "function",
    "role": "Sub",
    "name": "扰动战术/一切为了孩子",
    "meansName": "扰动战术",
    "meansCost": "1",
    "meansEffect": "交换一方2名角色的位置。",
    "billName": "一切为了孩子",
    "billEffect": "资源最低的所有角色影响力+4",
    "bound": "红冠母亲团",
    "image": "assets/cards/Red_Base_Sub_03.webp",
    "altImage": null,
    "pairId": "Red_Base_Leader_03"
  },
  {
    "id": "Red_Base_Leader_04",
    "color": "红",
    "colorKey": "red",
    "type": "character",
    "role": "Leader",
    "name": "鸽拉松",
    "animal": "禽",
    "recruit": "2",
    "passive": "竞选阶段，如果鸽拉松横置，你的其它角色影响力+2。",
    "declName": "胜利讯息",
    "declCost": "1",
    "declEffect": "横置鸽拉松，摸1张牌。",
    "bound": "鸽毛信/通讯架构",
    "tags": "",
    "image": "assets/cards/Red_Base_Leader_04.webp",
    "altImage": null,
    "pairId": "Red_Base_Sub_04"
  },
  {
    "id": "Red_Base_Sub_04",
    "color": "红",
    "colorKey": "red",
    "type": "function",
    "role": "Sub",
    "name": "鸽毛信/新航线",
    "meansName": "鸽毛信",
    "meansCost": "1",
    "meansEffect": "摸1张牌，然后将鸽毛信放置在牌堆顶。",
    "billName": "新航线",
    "billEffect": "行动阶段，双方获得以下可选行动：移动一名角色，每回合限一次。",
    "bound": "鸽拉松",
    "image": "assets/cards/Red_Base_Sub_04.webp",
    "altImage": null,
    "pairId": "Red_Base_Leader_04"
  },
  {
    "id": "Red_Base_Leader_05",
    "color": "红",
    "colorKey": "red",
    "type": "character",
    "role": "Leader",
    "name": "灰耗子",
    "animal": "鼠",
    "recruit": "1",
    "passive": "灰耗子进场时，夺取对位1个资源。",
    "declName": "地下联络网",
    "declCost": "0",
    "declEffect": "你的红色角色{募集1}。",
    "bound": "地下组织/团体游行法案",
    "tags": "",
    "image": "assets/cards/Red_Base_Leader_05.webp",
    "altImage": null,
    "pairId": "Red_Base_Sub_05"
  },
  {
    "id": "Red_Base_Sub_05",
    "color": "红",
    "colorKey": "red",
    "type": "function",
    "role": "Sub",
    "name": "地下组织/通讯架构",
    "meansName": "地下组织",
    "meansCost": "2",
    "meansEffect": "将一名红色角色从弃牌堆打出进场。",
    "billName": "通讯架构",
    "billEffect": "角色宣言时可以{消耗}其它同色角色的资源。",
    "bound": "灰耗子",
    "image": "assets/cards/Red_Base_Sub_05.webp",
    "altImage": null,
    "pairId": "Red_Base_Leader_05"
  },
  {
    "id": "Yellow_Base_Leader_01",
    "color": "黄",
    "colorKey": "yellow",
    "type": "character",
    "role": "Leader",
    "name": "莫莉",
    "animal": "马",
    "recruit": "4",
    "passive": "莫莉的影响力-4；莫莉所在选区任意一方完胜时选票-1。",
    "declName": "人类的恩赐",
    "declCost": "0",
    "declEffect": "若莫莉影响力为0{募集2}。",
    "bound": "逃离庄园/保留私有财产",
    "tags": "",
    "image": "assets/cards/Yellow_Base_Leader_01.webp",
    "altImage": "assets/cards/Yellow_Base_Leader_01_alt.webp",
    "pairId": "Yellow_Base_Sub_01"
  },
  {
    "id": "Yellow_Base_Sub_01",
    "color": "黄",
    "colorKey": "yellow",
    "type": "function",
    "role": "Sub",
    "name": "逃离庄园/保留私有财产",
    "meansName": "逃离庄园",
    "meansCost": "2",
    "meansEffect": "使你的一名角色回手。",
    "billName": "保留私有财产",
    "billEffect": "维持阶段离场结算前，没有资源的角色{募集1}。",
    "bound": "莫莉",
    "image": "assets/cards/Yellow_Base_Sub_01.webp",
    "altImage": null,
    "pairId": "Yellow_Base_Leader_01"
  },
  {
    "id": "Yellow_Base_Leader_02",
    "color": "黄",
    "colorKey": "yellow",
    "type": "character",
    "role": "Leader",
    "name": "那只猫",
    "animal": "猫",
    "recruit": "4",
    "passive": "{条约X}；竞选阶段，那只猫获得X票（X为对位本回合得票）.",
    "declName": "两头下注",
    "declCost": "2",
    "declEffect": "为那只猫和对位各{募集2}，由你选择募集来源。",
    "bound": "乘虚而入/贸易税",
    "tags": "",
    "image": "assets/cards/Yellow_Base_Leader_02.webp",
    "altImage": null,
    "pairId": "Yellow_Base_Sub_02"
  },
  {
    "id": "Yellow_Base_Sub_02",
    "color": "黄",
    "colorKey": "yellow",
    "type": "function",
    "role": "Sub",
    "name": "乘虚而入/贸易税",
    "meansName": "乘虚而入",
    "meansCost": "2",
    "meansEffect": "移动1名角色，重置或横置目标选区的双方角色。",
    "billName": "贸易税",
    "billEffect": "执行带有募集、转移资源、夺取效果的行动时，对手{募集1}.",
    "bound": "那只猫",
    "image": "assets/cards/Yellow_Base_Sub_02.webp",
    "altImage": null,
    "pairId": "Yellow_Base_Leader_02"
  },
  {
    "id": "Yellow_Base_Leader_03",
    "color": "黄",
    "colorKey": "yellow",
    "type": "character",
    "role": "Leader",
    "name": "金不换",
    "animal": "禽",
    "recruit": "5",
    "passive": "金不换的维持费用恒为1.",
    "declName": "铁公鸡",
    "declCost": "0",
    "declEffect": "金不换{募集1}。",
    "bound": "资产转移/财政紧缩",
    "tags": "",
    "image": "assets/cards/Yellow_Base_Leader_03.webp",
    "altImage": null,
    "pairId": "Yellow_Base_Sub_03"
  },
  {
    "id": "Yellow_Base_Sub_03",
    "color": "黄",
    "colorKey": "yellow",
    "type": "function",
    "role": "Sub",
    "name": "资产转移/财政紧缩",
    "meansName": "资产转移",
    "meansCost": "0",
    "meansEffect": "{抢先}；从你的1名角色上转移任意数量的资源至你的另一名角色。",
    "billName": "财政紧缩",
    "billEffect": "所有角色资源不可被夺取或由行动效果{消耗}。",
    "bound": "金不换",
    "image": "assets/cards/Yellow_Base_Sub_03.webp",
    "altImage": null,
    "pairId": "Yellow_Base_Leader_03"
  },
  {
    "id": "Yellow_Base_Leader_04",
    "color": "黄",
    "colorKey": "yellow",
    "type": "character",
    "role": "Leader",
    "name": "波拉尼奥",
    "animal": "犬",
    "recruit": "3",
    "passive": "{条约2}；竞选阶段，本选区双方影响力差不超过4时视为平局。",
    "declName": "化解纠纷",
    "declCost": "2",
    "declEffect": "横置波拉尼奥与对位。",
    "bound": "欺软怕硬/商品化和平",
    "tags": "",
    "image": "assets/cards/Yellow_Base_Leader_04.webp",
    "altImage": null,
    "pairId": "Yellow_Base_Sub_04"
  },
  {
    "id": "Yellow_Base_Sub_04",
    "color": "黄",
    "colorKey": "yellow",
    "type": "function",
    "role": "Sub",
    "name": "欺软怕硬/商品化和平",
    "meansName": "欺软怕硬",
    "meansCost": "1",
    "meansEffect": "选择一名角色，资源不高于它的角色{消耗1}，资源高于它的角色{募集1}。",
    "billName": "商品化和平",
    "billEffect": "竞选阶段开始时，双方可以{消耗5}使一个选区视为平局。",
    "bound": "波拉尼奥",
    "image": "assets/cards/Yellow_Base_Sub_04.webp",
    "altImage": null,
    "pairId": "Yellow_Base_Leader_04"
  },
  {
    "id": "Yellow_Base_Leader_05",
    "color": "黄",
    "colorKey": "yellow",
    "type": "character",
    "role": "Leader",
    "name": "货郎稀奇",
    "animal": "禽",
    "recruit": "5",
    "passive": "对手也可使用货郎稀奇的宣言；货郎稀奇可以代替其他角色支付维持费用。",
    "declName": "公平贸易",
    "declCost": "0",
    "declEffect": "{勤奋}；将你的1名角色的2个资源转移给货郎稀奇，然后重整该角色。",
    "bound": "头奖/集换中心",
    "tags": "",
    "image": "assets/cards/Yellow_Base_Leader_05.webp",
    "altImage": null,
    "pairId": "Yellow_Base_Sub_05"
  },
  {
    "id": "Yellow_Base_Sub_05",
    "color": "黄",
    "colorKey": "yellow",
    "type": "function",
    "role": "Sub",
    "name": "头奖/集换中心",
    "meansName": "头奖",
    "meansCost": "1",
    "meansEffect": "声明1张卡牌，{审查}牌堆顶1张牌，若与声明卡牌一致，选择你的1个角色，其竞选阶段额外获得1票。",
    "billName": "集换中心",
    "billEffect": "行动阶段，为双方玩家增加以下可选行动：将1名角色的全部资源转移至对手角色，然后你的该角色回手。",
    "bound": "货郎稀奇",
    "image": "assets/cards/Yellow_Base_Sub_05.webp",
    "altImage": null,
    "pairId": "Yellow_Base_Leader_05"
  },
  {
    "id": "Yellow_SP_Leader_01",
    "color": "黄",
    "colorKey": "yellow",
    "type": "character",
    "role": "Leader",
    "name": "唐纳德鸭",
    "animal": "禽",
    "recruit": "5",
    "passive": "对位角色宣言后，解除唐纳德鸭的疲劳状态。",
    "declName": "让庄园再次伟大",
    "declCost": "2",
    "declEffect": "再次执行你的上一个行动效果。",
    "bound": "",
    "tags": "",
    "image": null,
    "altImage": null,
    "pairId": "Yellow_SP_Sub_01"
  },
  {
    "id": "Yellow_SP_Sub_01",
    "color": "黄",
    "colorKey": "yellow",
    "type": "function",
    "role": "Sub",
    "name": "永远在赢/反移民政策",
    "meansName": "永远在赢",
    "meansCost": "3",
    "meansEffect": "选择1个选区，该选区竞选失败时视为平局。",
    "billName": "反移民政策",
    "billEffect": "在场角色较多的一方无法移动，且不能打出角色进场。",
    "bound": "唐纳德鸭",
    "image": null,
    "altImage": null,
    "pairId": "Yellow_SP_Leader_01"
  },
  {
    "id": "Blue_Base_Leader_01",
    "color": "蓝",
    "colorKey": "blue",
    "type": "character",
    "role": "Leader",
    "name": "吱嘎",
    "animal": "猪",
    "recruit": "3",
    "passive": "每当1张{已审查}的牌被打出或弃置，吱嘎{募集1}。",
    "declName": "公正公开",
    "declCost": "1",
    "declEffect": "{审查}对手1张手牌或你的1张在场角色牌。",
    "bound": "午夜修宪/新七诫",
    "tags": "",
    "image": "assets/cards/Blue_Base_Leader_01.webp",
    "altImage": null,
    "pairId": "Blue_Base_Sub_01"
  },
  {
    "id": "Blue_Base_Sub_01",
    "color": "蓝",
    "colorKey": "blue",
    "type": "function",
    "role": "Sub",
    "name": "午夜修宪/新七诫",
    "meansName": "午夜修宪",
    "meansCost": "0",
    "meansEffect": "将1张被覆盖的议案牌置顶。",
    "billName": "新七诫",
    "billEffect": "{已审查}的功能牌无法作为手段打出或弃置募集资金。",
    "bound": "吱嘎",
    "image": "assets/cards/Blue_Base_Sub_01.webp",
    "altImage": null,
    "pairId": "Blue_Base_Leader_01"
  },
  {
    "id": "Blue_Base_Leader_02",
    "color": "蓝",
    "colorKey": "blue",
    "type": "character",
    "role": "Leader",
    "name": "摩西",
    "animal": "禽",
    "recruit": "3",
    "passive": "摩西的对位无法使用宣言行动。",
    "declName": "净化心灵",
    "declCost": "2",
    "declEffect": "双方各弃1张牌，然后{审查}各自牌堆顶1张牌。",
    "bound": "神父的告解室/蜜糖山传说",
    "tags": "",
    "image": "assets/cards/Blue_Base_Leader_02.webp",
    "altImage": null,
    "pairId": "Blue_Base_Sub_02"
  },
  {
    "id": "Blue_Base_Sub_02",
    "color": "蓝",
    "colorKey": "blue",
    "type": "function",
    "role": "Sub",
    "name": "神父的告解室/蜜糖山传说",
    "meansName": "神父的告解室",
    "meansCost": "2",
    "meansEffect": "由你的对手执行2次选择：\n①{审查}其1张手牌。\n②{审查}你牌堆顶1张牌。",
    "billName": "蜜糖山传说",
    "billEffect": "资源获取阶段，玩家可以选择少摸1张牌，然后将3个自然资源分配给任意角色。",
    "bound": "摩西",
    "image": "assets/cards/Blue_Base_Sub_02.webp",
    "altImage": null,
    "pairId": "Blue_Base_Leader_02"
  },
  {
    "id": "Blue_Base_Leader_03",
    "color": "蓝",
    "colorKey": "blue",
    "type": "character",
    "role": "Leader",
    "name": "变色龙",
    "animal": "爬行",
    "recruit": "3",
    "passive": "任何功能牌或宣言的消耗都可以由变色龙支付。",
    "declName": "拟态转播",
    "declCost": "0",
    "declEffect": "选择场上或{已审查}角色的1个宣言行动，由变色龙免费执行。",
    "bound": "两面派/新闻学联盟",
    "tags": "",
    "image": "assets/cards/Blue_Base_Leader_03.webp",
    "altImage": null,
    "pairId": "Blue_Base_Sub_03"
  },
  {
    "id": "Blue_Base_Sub_03",
    "color": "蓝",
    "colorKey": "blue",
    "type": "function",
    "role": "Sub",
    "name": "两面派/新闻学联盟",
    "meansName": "两面派",
    "meansCost": "1",
    "meansEffect": "{审查}对手1张手牌，若为角色牌，你可以{审查}1名在场角色；若为功能牌，可以视为由你免费打出。",
    "billName": "新闻学联盟",
    "billEffect": "{已审查}的功能牌可以由双方支付费用并打出（无视颜色）。",
    "bound": "变色龙",
    "image": "assets/cards/Blue_Base_Sub_03.webp",
    "altImage": null,
    "pairId": "Blue_Base_Leader_03"
  },
  {
    "id": "Blue_Base_Leader_04",
    "color": "蓝",
    "colorKey": "blue",
    "type": "character",
    "role": "Leader",
    "name": "穆里埃尔",
    "animal": "羊",
    "recruit": "3",
    "passive": "每当一张牌被{审查}时，穆里埃尔{募集1}。",
    "declName": "见证",
    "declCost": "1",
    "declEffect": "{审查}对手1张手牌，如果是角色牌，可以额外{审查}对手1张手牌。",
    "bound": "缄默不言/记录在案",
    "tags": "",
    "image": "assets/cards/Blue_Base_Leader_04.webp",
    "altImage": null,
    "pairId": "Blue_Base_Sub_04"
  },
  {
    "id": "Blue_Base_Sub_04",
    "color": "蓝",
    "colorKey": "blue",
    "type": "function",
    "role": "Sub",
    "name": "缄默不言/记录在案",
    "meansName": "视若无睹",
    "meansCost": "2",
    "meansEffect": "{审查}对手至多3张手牌，对手的下一个行动具有{抢先}。",
    "billName": "记录在案",
    "billEffect": "行动阶段开始时，双方{审查}弃牌堆顶的1张牌。",
    "bound": "穆里埃尔",
    "image": "assets/cards/Blue_Base_Sub_04.webp",
    "altImage": null,
    "pairId": "Blue_Base_Leader_04"
  },
  {
    "id": "Blue_Base_Leader_05",
    "color": "蓝",
    "colorKey": "blue",
    "type": "character",
    "role": "Leader",
    "name": "绵羊合唱团",
    "animal": "羊",
    "recruit": "4",
    "passive": "对手的所有可使用的宣言具有{独裁}。",
    "declName": "四条腿好",
    "declCost": "2",
    "declEffect": "选择1名角色，其{募集4}，然后将其横置。",
    "bound": "两条腿更好/领袖宣传费",
    "tags": "",
    "image": "assets/cards/Blue_Base_Leader_05.webp",
    "altImage": null,
    "pairId": "Blue_Base_Sub_05"
  },
  {
    "id": "Blue_Base_Sub_05",
    "color": "蓝",
    "colorKey": "blue",
    "type": "function",
    "role": "Sub",
    "name": "两条腿更好/领袖宣传费",
    "meansName": "两条腿更好",
    "meansCost": "1",
    "meansEffect": "选择一名角色{消耗2}，然后将其重整。",
    "billName": "领袖宣传费",
    "billEffect": "行动阶段结束时，影响力最高的角色进行一次维持费用结算。",
    "bound": "绵羊合唱团",
    "image": "assets/cards/Blue_Base_Sub_05.webp",
    "altImage": null,
    "pairId": "Blue_Base_Leader_05"
  },
  {
    "id": "Green_Base_Leader_01",
    "color": "绿",
    "colorKey": "green",
    "type": "character",
    "role": "Leader",
    "name": "拳击手",
    "animal": "马",
    "recruit": "4",
    "passive": "拳击手{消耗}时，其中1个资源改为从自然资源消耗。（横置时改为2个）",
    "declName": "加倍劳作",
    "declCost": "2",
    "declEffect": "{勤奋}；横置拳击手，摸1张牌，你的其他绿色角色各获得1个自然资源。",
    "bound": "不眠不休/风车蓝图",
    "tags": "",
    "image": "assets/cards/Green_Base_Leader_01.webp",
    "altImage": null,
    "pairId": "Green_Base_Sub_01"
  },
  {
    "id": "Green_Base_Sub_01",
    "color": "绿",
    "colorKey": "green",
    "type": "function",
    "role": "Sub",
    "name": "不眠不休/风车蓝图",
    "meansName": "不眠不休",
    "meansCost": "1",
    "meansEffect": "选择1名角色，将其{竖置}或解除其{疲劳}。若其为绿，则获得1个自然资源。",
    "billName": "风车蓝图",
    "billEffect": "行动阶段结束时，所有绿色角色获得2个自然资源。",
    "bound": "拳击手",
    "image": "assets/cards/Green_Base_Sub_01.webp",
    "altImage": null,
    "pairId": "Green_Base_Leader_01"
  },
  {
    "id": "Green_Base_Leader_02",
    "color": "绿",
    "colorKey": "green",
    "type": "character",
    "role": "Leader",
    "name": "苜蓿",
    "animal": "马",
    "recruit": "3",
    "passive": "你的另一名角色离场时，若其还有资源，则转移至苜蓿。",
    "declName": "自然庇护所",
    "declCost": "1",
    "declEffect": "选择1名角色，每有1个空位其获得1个自然资源，若其为绿则额外获得1个。",
    "bound": "警觉/平民互助会",
    "tags": "",
    "image": "assets/cards/Green_Base_Leader_02.webp",
    "altImage": null,
    "pairId": "Green_Base_Sub_02"
  },
  {
    "id": "Green_Base_Sub_02",
    "color": "绿",
    "colorKey": "green",
    "type": "function",
    "role": "Sub",
    "name": "警觉/平民互助会",
    "meansName": "警觉",
    "meansCost": "2",
    "meansEffect": "由你选择双方各1名角色回手。",
    "billName": "平民互助会",
    "billEffect": "空位的影响力视为3。",
    "bound": "苜蓿",
    "image": "assets/cards/Green_Base_Sub_02.webp",
    "altImage": null,
    "pairId": "Green_Base_Leader_02"
  },
  {
    "id": "Green_Base_Leader_03",
    "color": "绿",
    "colorKey": "green",
    "type": "character",
    "role": "Leader",
    "name": "小树枝",
    "animal": "水生",
    "recruit": "2",
    "passive": "小树枝离场时改为回手。",
    "declName": "生生不息",
    "declCost": "2",
    "declEffect": "{抢先}；使小树枝离场。",
    "bound": "老树枝",
    "tags": "",
    "image": "assets/cards/Green_Base_Leader_03.webp",
    "altImage": null,
    "pairId": "Green_Base_Sub_03"
  },
  {
    "id": "Green_Base_Sub_03",
    "color": "绿",
    "colorKey": "green",
    "type": "character",
    "role": "Sub",
    "name": "老树枝",
    "animal": "水生",
    "recruit": "3",
    "passive": "打出老树枝的行动视为具有{抢先}。",
    "declName": "快速召回",
    "declCost": "2",
    "declEffect": "{抢先}；从弃牌堆选择1名角色回手。",
    "bound": "小树枝",
    "tags": "",
    "image": "assets/cards/Green_Base_Sub_03.webp",
    "altImage": null,
    "pairId": "Green_Base_Leader_03"
  },
  {
    "id": "Green_Base_Leader_04",
    "color": "绿",
    "colorKey": "green",
    "type": "character",
    "role": "Leader",
    "name": "本杰明",
    "animal": "驴",
    "recruit": "3",
    "passive": "本杰明无法被选择。",
    "declName": "与世无争",
    "declCost": "1",
    "declEffect": "使1名角色{疲劳}。",
    "bound": "冷眼旁观/无政府主义",
    "tags": "",
    "image": "assets/cards/Green_Base_Leader_04.webp",
    "altImage": null,
    "pairId": "Green_Base_Sub_04"
  },
  {
    "id": "Green_Base_Sub_04",
    "color": "绿",
    "colorKey": "green",
    "type": "function",
    "role": "Sub",
    "name": "冷眼旁观/无政府主义",
    "meansName": "冷眼旁观",
    "meansCost": "2",
    "meansEffect": "重整1名角色，若其不为绿，使其{疲劳}。",
    "billName": "无政府主义",
    "billEffect": "竞选阶段，所有选区获得的选票-1.",
    "bound": "本杰明",
    "image": "assets/cards/Green_Base_Sub_04.webp",
    "altImage": null,
    "pairId": "Green_Base_Leader_04"
  },
  {
    "id": "Green_Base_Leader_05",
    "color": "绿",
    "colorKey": "green",
    "type": "character",
    "role": "Leader",
    "name": "五桶合作社",
    "animal": "奶牛",
    "recruit": "5",
    "passive": "行动阶段开始时，自然资源中每有5个资源，五桶合作社{募集1}。",
    "declName": "每天一斤奶",
    "declCost": "1",
    "declEffect": "{抢先}；使你的下一个行动具有{抢先}。",
    "bound": "自由放牧/牧场计划",
    "tags": "",
    "image": "assets/cards/Green_Base_Leader_05.webp",
    "altImage": null,
    "pairId": "Green_Base_Sub_05"
  },
  {
    "id": "Green_Base_Sub_05",
    "color": "绿",
    "colorKey": "green",
    "type": "function",
    "role": "Sub",
    "name": "自由放牧/牧场计划",
    "meansName": "自由放牧",
    "meansCost": "2",
    "meansEffect": "移动1名角色，若其为绿，则解除其{疲劳}。",
    "billName": "牧场计划",
    "billEffect": "空位的对位维持费用+4.",
    "bound": "五桶合作社",
    "image": "assets/cards/Green_Base_Sub_05.webp",
    "altImage": null,
    "pairId": "Green_Base_Leader_05"
  },
  {
    "id": "Purple_Base_Leader_01",
    "color": "紫",
    "colorKey": "purple",
    "type": "character",
    "role": "Leader",
    "name": "拿破仑",
    "animal": "猪",
    "recruit": "4",
    "passive": "拿破仑对位的影响力-4",
    "declName": "肃清运动",
    "declCost": "3",
    "declEffect": "{独裁}；横置拿破仑对位角色。",
    "bound": "突击检查/宵禁令",
    "tags": "",
    "image": "assets/cards/Purple_Base_Leader_01.webp",
    "altImage": "assets/cards/Purple_Base_Leader_01_alt.webp",
    "pairId": "Purple_Base_Sub_01"
  },
  {
    "id": "Purple_Base_Sub_01",
    "color": "紫",
    "colorKey": "purple",
    "type": "function",
    "role": "Sub",
    "name": "突击检查/宵禁令",
    "meansName": "突击检查",
    "meansCost": "2",
    "meansEffect": "移动1名角色，然后横置对位角色。",
    "billName": "宵禁令",
    "billEffect": "行动阶段时，不能重整角色；重整阶段时，每名玩家最多重整1名角色。",
    "bound": "拿破仑",
    "image": "assets/cards/Purple_Base_Sub_01.webp",
    "altImage": null,
    "pairId": "Purple_Base_Leader_01"
  },
  {
    "id": "Purple_Base_Leader_02",
    "color": "紫",
    "colorKey": "purple",
    "type": "character",
    "role": "Leader",
    "name": "粉眼",
    "animal": "猪",
    "recruit": "3",
    "passive": "粉眼离场时，横置对位角色。",
    "declName": "以身殉职",
    "declCost": "1",
    "declEffect": "选择你的1名角色，将其资源全部转移给另一名角色。",
    "bound": "替死鬼/领袖高于一切",
    "tags": "",
    "image": "assets/cards/Purple_Base_Leader_02.webp",
    "altImage": null,
    "pairId": "Purple_Base_Sub_02"
  },
  {
    "id": "Purple_Base_Sub_02",
    "color": "紫",
    "colorKey": "purple",
    "type": "function",
    "role": "Sub",
    "name": "替死鬼/领袖高于一切",
    "meansName": "替死鬼",
    "meansCost": "1",
    "meansEffect": "交换你的2个同色角色的位置。",
    "billName": "领袖高于一切",
    "billEffect": "竞选阶段，影响力最高的角色胜利时视为{完胜}。",
    "bound": "粉眼",
    "image": "assets/cards/Purple_Base_Sub_02.webp",
    "altImage": null,
    "pairId": "Purple_Base_Leader_02"
  },
  {
    "id": "Purple_Base_Leader_03",
    "color": "紫",
    "colorKey": "purple",
    "type": "character",
    "role": "Leader",
    "name": "小小田",
    "animal": "犬",
    "recruit": "3",
    "passive": "任意角色重置时，你可以弃一张牌，取消这次重置。",
    "declName": "执法必严",
    "declCost": "2",
    "declEffect": "{独裁}；选择1名{疲劳}角色离场。",
    "bound": "追猎/墓地税",
    "tags": "",
    "image": "assets/cards/Purple_Base_Leader_03.webp",
    "altImage": null,
    "pairId": "Purple_Base_Sub_03"
  },
  {
    "id": "Purple_Base_Sub_03",
    "color": "紫",
    "colorKey": "purple",
    "type": "function",
    "role": "Sub",
    "name": "追猎/墓地税",
    "meansName": "追猎",
    "meansCost": "1",
    "meansEffect": "选择1名对手角色，对手必须将其移动，否则横置该角色。",
    "billName": "墓地税",
    "billEffect": "角色横置或离场时，若其还有资源，需要将2个资源转移至对位。",
    "bound": "小小田",
    "image": "assets/cards/Purple_Base_Sub_03.webp",
    "altImage": null,
    "pairId": "Purple_Base_Leader_03"
  },
  {
    "id": "Purple_Base_Leader_04",
    "color": "紫",
    "colorKey": "purple",
    "type": "character",
    "role": "Leader",
    "name": "九犬护卫队",
    "animal": "犬",
    "recruit": "9",
    "passive": "九犬护卫队和{傀儡}每次失去资源时，{消耗1}。",
    "declName": "分则能成",
    "declCost": "3",
    "declEffect": "{傀儡4}.",
    "bound": "酷刑/游行禁令",
    "tags": "",
    "image": "assets/cards/Purple_Base_Leader_04.webp",
    "altImage": null,
    "pairId": "Purple_Base_Sub_04"
  },
  {
    "id": "Purple_Base_Sub_04",
    "color": "紫",
    "colorKey": "purple",
    "type": "function",
    "role": "Sub",
    "name": "酷刑/游行禁令",
    "meansName": "严刑拷打",
    "meansCost": "2",
    "meansEffect": "使1名角色影响力-5，若行动阶段结束时，其影响力为0，则立即离场。",
    "billName": "游行禁令",
    "billEffect": "角色不能移动或回手。",
    "bound": "九犬护卫队",
    "image": "assets/cards/Purple_Base_Sub_04.webp",
    "altImage": null,
    "pairId": "Purple_Base_Leader_04"
  },
  {
    "id": "Purple_Base_Leader_05",
    "color": "紫",
    "colorKey": "purple",
    "type": "character",
    "role": "Leader",
    "name": "公牛将军",
    "animal": "牛",
    "recruit": "5",
    "passive": "公牛将军完胜时，额外获得1选票。",
    "declName": "一往无前",
    "declCost": "1",
    "declEffect": "{独裁}；移动公牛将军，然后目标选区进行一次维持费用结算。",
    "bound": "全票通过/大独裁者",
    "tags": "",
    "image": "assets/cards/Purple_Base_Leader_05.webp",
    "altImage": null,
    "pairId": "Purple_Base_Sub_05"
  },
  {
    "id": "Purple_Base_Sub_05",
    "color": "紫",
    "colorKey": "purple",
    "type": "function",
    "role": "Sub",
    "name": "全票通过/大独裁者",
    "meansName": "全票通过",
    "meansCost": "2",
    "meansEffect": "{独裁}；立即结束行动阶段",
    "billName": "勇者斗兽场",
    "billEffect": "宣言具有{独裁}的角色影响力+5，其对位影响力-5.",
    "bound": "公牛将军",
    "image": "assets/cards/Purple_Base_Sub_05.webp",
    "altImage": null,
    "pairId": "Purple_Base_Leader_05"
  },
  {
    "id": "Purple_SP_Leader_01",
    "color": "紫",
    "colorKey": "purple",
    "type": "character",
    "role": "Leader",
    "name": "肥头",
    "animal": "猪",
    "recruit": "3",
    "passive": "肥头离场时，可以将肥头二号从任意位置打出至本选区。",
    "declName": "纯正血统",
    "declCost": "1",
    "declEffect": "{独裁}；从牌堆中检索1张猪角色加入手牌。",
    "bound": "肥头二号",
    "tags": "",
    "image": null,
    "altImage": null,
    "pairId": "Purple_SP_Sub_01"
  },
  {
    "id": "Purple_SP_Sub_01",
    "color": "紫",
    "colorKey": "purple",
    "type": "character",
    "role": "Sub",
    "name": "肥头二号",
    "animal": "猪",
    "recruit": "3",
    "passive": "肥头二号离场后，本回合你不能再打出角色至本选区。",
    "declName": "只有一个声音",
    "declCost": "2",
    "declEffect": "{独裁}；本回合所有角色不能发动宣言。",
    "bound": "肥头",
    "tags": "",
    "image": null,
    "altImage": null,
    "pairId": "Purple_SP_Leader_01"
  }
];
